export const events = [
	{
	  id: 1,
	  name: 'Faculty Meeting',
	  startDate: '2024-05-08T10:00',
	  endDate: '2024-05-10T12:00',
	  type: 'Administrative Event',
	  status: 'Completed',
	  creator: 'Dean John Smith',
	  groups: ['Faculty'],
	  isImportant: false,
	},
	{
	  id: 2,
	  name: 'Student Art Exhibition',
	  startDate: '2024-05-01T14:00',
	  endDate: '2024-05-06T18:00',
	  type: 'Cultural Event',
	  status: 'Completed',
	  creator: 'Prof. Jane Doe',
	  groups: ['Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: true,
	},
	{
	  id: 3,
	  name: 'Research Symposium',
	  startDate: '2024-05-03T09:00',
	  endDate: '2024-05-03T17:00',
	  type: 'Academic Event',
	  status: 'Completed',
	  creator: 'Dr. Michael Johnson',
	  groups: ['Faculty', 'Research Staff', 'Grad Students'],
	  isImportant: false,
	},
	{
	  id: 4,
	  name: 'Alumni Networking Event',
	  startDate: '2024-05-05T18:00',
	  endDate: '2024-05-05T21:00',
	  type: 'Social Event',
	  status: 'Completed',
	  creator: 'Alumni Relations Office',
	  groups: ['Alumni'],
	  isImportant: true,
	},
	{
	  id: 5,
	  name: 'Inter-College Soccer Tournament',
	  startDate: '2024-05-08T10:00',
	  endDate: '2024-05-12T18:00',
	  type: 'Sports Event',
	  status: 'In Progress',
	  creator: 'Coach Sarah Thompson',
	  groups: ['Athletes', 'Sports Club Members'],
	  isImportant: false,
	},
	{
	  id: 6,
	  name: 'Board of Trustees Meeting',
	  startDate: '2024-05-10T09:00',
	  endDate: '2024-05-10T15:00',
	  type: 'Administrative Event',
	  status: 'Upcoming',
	  creator: 'Secretary Lisa Brown',
	  groups: ['Board Members', 'Senior Administration'],
	  isImportant: true,
	},
	{
	  id: 7,
	  name: 'Music Department Concert',
	  startDate: '2024-05-12T19:00',
	  endDate: '2024-05-12T22:00',
	  type: 'Cultural Event',
	  status: 'Upcoming',
	  creator: 'Dr. Emily Davis',
	  groups: ['Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: false,
	},
	{
	  id: 8,
	  name: 'Graduation Ceremony',
	  startDate: '2024-05-15T10:00',
	  endDate: '2024-05-15T13:00',
	  type: 'Academic Event',
	  status: 'Upcoming',
	  creator: 'Academic Affairs Office',
	  groups: ['Graduating Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: true,
	},
	{
	  id: 9,
	  name: 'Faculty Workshop',
	  startDate: '2024-05-17T14:00',
	  endDate: '2024-05-17T16:00',
	  type: 'Administrative Event',
	  status: 'Upcoming',
	  creator: 'Prof. David Wilson',
	  groups: ['Faculty'],
	  isImportant: false,
	},
	{
	  id: 10,
	  name: 'Student Government Elections',
	  startDate: '2024-05-18T09:00',
	  endDate: '2024-05-18T17:00',
	  type: 'Administrative Event',
	  status: 'Upcoming',
	  creator: 'Student Government Association',
	  groups: ['Students'],
	  isImportant: true,
	},
	{
	  id: 11,
	  name: 'Theater Department Play',
	  startDate: '2024-05-19T19:00',
	  endDate: '2024-05-21T22:00',
	  type: 'Cultural Event',
	  status: 'Upcoming',
	  creator: 'Prof. Olivia Anderson',
	  groups: ['Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: false,
	},
	{
	  id: 12,
	  name: 'Community Service Day',
	  startDate: '2024-05-22T08:00',
	  endDate: '2024-05-22T17:00',
	  type: 'Social Event',
	  status: 'Upcoming',
	  creator: 'Community Outreach Office',
	  groups: ['Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: true,
	},
	{
	  id: 13,
	  name: 'Research Grant Deadline',
	  startDate: '2024-05-24T23:59',
	  endDate: '2024-05-24T23:59',
	  type: 'Administrative Event',
	  status: 'Upcoming',
	  creator: 'Research Administration',
	  groups: ['Faculty', 'Research Staff'],
	  isImportant: false,
	},
	{
	  id: 14,
	  name: 'Student Art Exhibition Reception',
	  startDate: '2024-05-26T17:00',
	  endDate: '2024-05-26T19:00',
	  type: 'Cultural Event',
	  status: 'Upcoming',
	  creator: 'Prof. Jane Doe',
	  groups: ['Students', 'Faculty', 'Staff', 'Alumni'],
	  isImportant: true,
	},
	{
	  id: 15,
	  name: 'Memorial Day (No Classes)',
	  startDate: '2024-05-29T00:00',
	  endDate: '2024-05-29T23:59',
	  type: 'Administrative Event',
	  status: 'Upcoming',
	  creator: 'Academic Affairs Office',
	  groups: ['Students', 'Faculty', 'Staff'],
	  isImportant: false,
	},
  ];