import type { IInfo, ISearchPersonWorker, ISearchPersonStudent } from "./Search.page";

export const groups: IInfo[] = [
	{ id: 1, shortName: 'ИП-21', fullName: 'Информатика и программирование' },
	{ id: 2, shortName: 'ИП-22', fullName: 'Информатика и программирование' },
	{ id: 3, shortName: 'ЭМ-31', fullName: 'Экономика и менеджмент' },
	{ id: 4, shortName: 'ГУП-41', fullName: 'Государственное управление и политология' },
	{ id: 5, shortName: 'ГУП-42', fullName: 'Государственное управление и политология' },
	{ id: 6, shortName: 'ГУП-43', fullName: 'Государственное управление и политология' },
	{ id: 7, shortName: 'ПМВ-21', fullName: 'Прикладная математика и вычислительная техника' },
	{ id: 8, shortName: 'ЛП-31', fullName: 'Лингвистика и перевод' },
	{ id: 9, shortName: 'ЛП-32', fullName: 'Лингвистика и перевод' },
	{ id: 10, shortName: 'ЛП-33', fullName: 'Лингвистика и перевод' },
	{ id: 11, shortName: 'ИТК-21', fullName: 'Информационные технологии и кибербезопасность' },
	{ id: 12, shortName: 'ИТК-22', fullName: 'Информационные технологии и кибербезопасность' },
	{ id: 13, shortName: 'БТМ-41', fullName: 'Бизнес и технологический менеджмент' },
	{ id: 14, shortName: 'БТМ-42', fullName: 'Бизнес и технологический менеджмент' },
	{ id: 15, shortName: 'БТМ-43', fullName: 'Бизнес и технологический менеджмент' },
	{ id: 16, shortName: 'СИС-31', fullName: 'Социальные исследования и статистика' },
	{ id: 17, shortName: 'СИС-32', fullName: 'Социальные исследования и статистика' }
  ];
  
  export const faculties: IInfo[] = [
	{ id: 1, shortName: 'ФИТ', fullName: 'Факультет Информационных Технологий' },
	{ id: 2, shortName: 'ФУиЭ', fullName: 'Факультет Управления и Экономики' },
	{ id: 3, shortName: 'ФМиВТ', fullName: 'Факультет Математики и Вычислительной Техники' },
	{ id: 4, shortName: 'ФЛиП', fullName: 'Факультет Лингвистики и Перевода' },
	{ id: 5, shortName: 'ФЭМ', fullName: 'Факультет Экономики и Менеджмента' },
	{ id: 6, shortName: 'ФФиП', fullName: 'Факультет Философии и Психологии' },
	{ id: 7, shortName: 'ФПиА', fullName: 'Факультет Права и Администрации' },
	{ id: 8, shortName: 'ФХиБ', fullName: 'Факультет Химии и Биологии' }
  ];
  
/*   const persons: ISearchPersonWorker[] = [
	// Проректор
	{ id: 1, firstName: 'Мария', lastName: 'Смирнова', surName: 'Игоревна', role: 'Проректор', scienceDegree: 'Доктор наук', faculty: faculties[1] },
  
	// Деканы
	{ id: 2, firstName: 'Алексей', lastName: 'Иванов', surName: 'Петрович', role: 'Декан', scienceDegree: 'Профессор', faculty: faculties[0] },
	{ id: 3, firstName: 'Дмитрий', lastName: 'Соколов', surName: 'Николаевич', role: 'Декан', scienceDegree: 'Профессор', faculty: faculties[1] },
	{ id: 4, firstName: 'Иван', lastName: 'Козлов', surName: 'Петрович', role: 'Декан', scienceDegree: 'Профессор', faculty: faculties[2] },
	{ id: 5, firstName: 'Екатерина', lastName: 'Новикова', surName: 'Андреевна', role: 'Декан', scienceDegree: 'Профессор', faculty: faculties[3] },
  
	// зав.Кафедры
	{ id: 6, firstName: 'Ольга', lastName: 'Попова', surName: 'Владимировна', role: 'зав.Кафедры', scienceDegree: 'Доцент', faculty: faculties[0] },
	{ id: 7, firstName: 'Анна', lastName: 'Лебедева', surName: 'Сергеевна', role: 'зав.Кафедры', scienceDegree: 'Ассистент', faculty: faculties[0] },
	{ id: 8, firstName: 'Максим', lastName: 'Морозов', surName: 'Викторович', role: 'зав.Кафедры', scienceDegree: 'Старший преподаватель', faculty: faculties[1] },
	{ id: 9, firstName: 'Сергей', lastName: 'Кузнецов', surName: 'Александрович', role: 'зав.Кафедры', scienceDegree: 'Кандидат наук', faculty: faculties[1] },
	{ id: 10, firstName: 'Татьяна', lastName: 'Воробьева', surName: 'Александровна', role: 'зав.Кафедры', scienceDegree: 'Лаборант', faculty: faculties[2] },
	{ id: 11, firstName: 'Григорий', lastName: 'Федоров', surName: 'Михайлович', role: 'зав.Кафедры', scienceDegree: 'Преподаватель', faculty: faculties[2] },
	{ id: 12, firstName: 'Елена', lastName: 'Михайлова', surName: 'Григорьевна', role: 'зав.Кафедры', scienceDegree: 'Старший преподаватель', faculty: faculties[3] },
  
	// Кураторы
	{ id: 13, firstName: 'Сергей', lastName: 'Кузнецов', surName: 'Александрович', role: 'Куратор', scienceDegree: 'Кандидат наук', faculty: faculties[0] },  
	{ id: 14, firstName: 'Дмитрий', lastName: 'Соколов', surName: 'Николаевич', role: 'Куратор', scienceDegree: 'Кандидат наук', faculty: faculties[0] },
	{ id: 15, firstName: 'Иван', lastName: 'Козлов', surName: 'Петрович', role: 'Куратор', scienceDegree: 'Доктор наук', faculty: faculties[1] },
	{ id: 16, firstName: 'Екатерина', lastName: 'Новикова', surName: 'Андреевна', role: 'Куратор', scienceDegree: 'Кандидат наук', faculty: faculties[1] },
	{ id: 17, firstName: 'Владимир', lastName: 'Богданов', surName: 'Иванович', role: 'Куратор', scienceDegree: 'Преподаватель', faculty: faculties[2] },
	{ id: 18, firstName: 'Татьяна', lastName: 'Воробьева', surName: 'Александровна', role: 'Куратор', scienceDegree: 'Лаборант', faculty: faculties[3] }, // Assuming one person can have multiple roles
	{ id: 19, firstName: 'Григорий', lastName: 'Федоров', surName: 'Михайлович', role: 'Куратор', scienceDegree: 'Преподаватель', faculty: faculties[3] },
	{ id: 20, firstName: 'Андрей', lastName: 'Зайцев', surName: 'Павлович', role: 'Куратор', scienceDegree: 'Преподаватель', faculty: faculties[0] },
	{ id: 21, firstName: 'Алина', lastName: 'Соловьева', surName: 'Романовна', role: 'Куратор', scienceDegree: 'Преподаватель', faculty: faculties[0] },
	{ id: 22, firstName: 'Роман', lastName: 'Петров', surName: 'Борисович', role: 'Куратор', scienceDegree: 'Старший преподаватель', faculty: faculties[1] },
	{ id: 23, firstName: 'Марина', lastName: 'Васильева', surName: 'Геннадьевна', role: 'Куратор', scienceDegree: 'Доцент', faculty: faculties[1] },
	{ id: 24, firstName: 'Павел', lastName: 'Александров', surName: 'Леонидович', role: 'Куратор', scienceDegree: 'Доцент', faculty: faculties[1] },
	{ id: 25, firstName: 'Людмила', lastName: 'Мартынова', surName: 'Евгеньевна', role: 'Куратор', scienceDegree: 'Старший преподаватель', faculty: faculties[2] },
	{ id: 26, firstName: 'Кирилл', lastName: 'Григорьев', surName: 'Степанович', role: 'Куратор', scienceDegree: 'Преподаватель', faculty: faculties[2] },
  
	// Работники
	{ id: 27, firstName: 'Вера', lastName: 'Афанасьева', surName: 'Романовна', role: 'Работник', scienceDegree: 'Старший преподаватель', faculty: faculties[3] },
	{ id: 28, firstName: 'Николай', lastName: 'Тихонов', surName: 'Сергеевич', role: 'Работник', scienceDegree: 'Академик', faculty: faculties[0] },
	{ id: 29, firstName: 'Игорь', lastName: 'Казаков', surName: 'Александрович', role: 'Работник', scienceDegree: 'Методист', faculty: faculties[1] },
	{ id: 30, firstName: 'София', lastName: 'Полякова', surName: 'Дмитриевна', role: 'Работник', scienceDegree: 'Преподаватель', faculty: faculties[2] },
	{ id: 31, firstName: 'Валентин', lastName: 'Кузьмин', surName: 'Владимирович', role: 'Работник', scienceDegree: 'Старший преподаватель', faculty: faculties[3] },
	{ id: 32, firstName: 'Лариса', lastName: 'Седова', surName: 'Игоревна', role: 'Работник', scienceDegree: 'Доцент', faculty: faculties[1] },
	{ id: 33, firstName: 'Галина', lastName: 'Жукова', surName: 'Олеговна', role: 'Работник', scienceDegree: 'Преподаватель', faculty: faculties[2] }
  ]; */

export const workers: ISearchPersonWorker[] = [
	{ id: 1, firstName: 'Алексей', lastName: 'Иванов', surName: 'Петрович', scienceDegree: 'Профессор', faculty: faculties[2], role: 'Декан' },
	{ id: 2, firstName: 'Мария', lastName: 'Смирнова', surName: 'Игоревна', scienceDegree: 'Доктор наук', faculty: faculties[2], role: 'Работник' },
	{ id: 3, firstName: 'Сергей', lastName: 'Кузнецов', surName: 'Александрович', scienceDegree: 'Преподаватель', faculty: faculties[2], role: 'Куратор' },
	{ id: 4, firstName: 'Ольга', lastName: 'Попова', surName: 'Владимировна', scienceDegree: 'Доцент', faculty: faculties[2], role: 'Зав. кафедры' },
	{ id: 5, firstName: 'Дмитрий', lastName: 'Соколов', surName: 'Николаевич', scienceDegree: 'Преподаватель', faculty: faculties[2], role: 'Куратор' },
	{ id: 6, firstName: 'Анна', lastName: 'Лебедева', surName: 'Сергеевна', scienceDegree: 'Ассистент', faculty: faculties[2], role: 'Работник' },
	{ id: 7, firstName: 'Иван', lastName: 'Козлов', surName: 'Петрович', scienceDegree: 'Преподаватель', faculty: faculties[1], role: 'Куратор' },
	{ id: 8, firstName: 'Екатерина', lastName: 'Новикова', surName: 'Андреевна', scienceDegree: 'Кандидат наук', faculty: faculties[1], role: 'Работник' },
	{ id: 9, firstName: 'Максим', lastName: 'Морозов', surName: 'Викторович', scienceDegree: 'Преподаватель', faculty: faculties[3], role: 'Куратор' },
	{ id: 10, firstName: 'Наталья', lastName: 'Павлова', surName: 'Дмитриевна', scienceDegree: 'Преподаватель', faculty: faculties[3], role: 'Куратор' },
	{ id: 11, firstName: 'Владимир', lastName: 'Богданов', surName: 'Иванович', scienceDegree: 'Преподаватель', faculty: faculties[3], role: 'Декан' },
	{ id: 12, firstName: 'Татьяна', lastName: 'Воробьева', surName: 'Александровна', scienceDegree: 'Лаборант', faculty: faculties[2], role: 'Работник' },
	{ id: 13, firstName: 'Григорий', lastName: 'Федоров', surName: 'Михайлович', scienceDegree: 'Преподаватель', faculty: faculties[5], role: 'Куратор' },
	{ id: 14, firstName: 'Елена', lastName: 'Михайлова', surName: 'Григорьевна', scienceDegree: 'Преподаватель', faculty: faculties[4], role: 'Куратор' },
	{ id: 15, firstName: 'Юрий', lastName: 'Николаев', surName: 'Васильевич', scienceDegree: 'Преподаватель', faculty: faculties[4], role: 'Куратор' },
	{ id: 16, firstName: 'Светлана', lastName: 'Макарова', surName: 'Игоревна', scienceDegree: 'Преподаватель', faculty: faculties[4], role: 'Декан' },
	{ id: 17, firstName: 'Андрей', lastName: 'Зайцев', surName: 'Павлович', scienceDegree: 'Преподаватель', faculty: faculties[5], role: 'Куратор' },
	{ id: 18, firstName: 'Алина', lastName: 'Соловьева', surName: 'Романовна', scienceDegree: 'Преподаватель', faculty: faculties[5], role: 'Куратор' },
	{ id: 19, firstName: 'Роман', lastName: 'Петров', surName: 'Борисович', scienceDegree: 'Преподаватель', faculty: faculties[6], role: 'Куратор' },
	{ id: 20, firstName: 'Марина', lastName: 'Васильева', surName: 'Геннадьевна', scienceDegree: 'Преподаватель', faculty: faculties[6], role: 'Куратор' },
	{ id: 21, firstName: 'Павел', lastName: 'Александров', surName: 'Леонидович', scienceDegree: 'Преподаватель', faculty: faculties[6], role: 'Зав. кафедры' },
	{ id: 22, firstName: 'Людмила', lastName: 'Мартынова', surName: 'Евгеньевна', scienceDegree: 'Преподаватель', faculty: faculties[7], role: 'Куратор' },
	{ id: 23, firstName: 'Кирилл', lastName: 'Григорьев', surName: 'Степанович', scienceDegree: 'Преподаватель', faculty: faculties[7], role: 'Куратор' },
	{ id: 24, firstName: 'Вера', lastName: 'Афанасьева', surName: 'Романовна', scienceDegree: 'Старший преподаватель', faculty: faculties[2], role: 'Работник' },
	{ id: 25, firstName: 'Николай', lastName: 'Тихонов', surName: 'Сергеевич', scienceDegree: 'Академик', faculty: faculties[0], role: 'Проректор' },
	{ id: 26, firstName: 'Игорь', lastName: 'Казаков', surName: 'Александрович', scienceDegree: 'Методист', faculty: faculties[0], role: 'Работник' },
	{ id: 27, firstName: 'София', lastName: 'Полякова', surName: 'Дмитриевна', scienceDegree: 'Преподаватель', faculty: faculties[1], role: 'Работник' },
	{ id: 28, firstName: 'Валентин', lastName: 'Кузьмин', surName: 'Владимирович', scienceDegree: 'Старший преподаватель', faculty: faculties[3], role: 'Работник' },
	{ id: 29, firstName: 'Лариса', lastName: 'Калинина', surName: 'Николаевна', scienceDegree: 'Доцент', faculty: faculties[3], role: 'Зав. кафедры' },
	{ id: 30, firstName: 'Станислав', lastName: 'Беляев', surName: 'Павлович', scienceDegree: 'Преподаватель', faculty: faculties[4], role: 'Работник' },
	{ id: 31, firstName: 'Анастасия', lastName: 'Горбунова', surName: 'Геннадьевна', scienceDegree: 'Преподаватель', faculty: faculties[5], role: 'Работник' },
	{ id: 32, firstName: 'Георгий', lastName: 'Терентьев', surName: 'Евгеньевич', scienceDegree: 'Старший преподаватель', faculty: faculties[6], role: 'Работник' },
	{ id: 33, firstName: 'Милана', lastName: 'Орлова', surName: 'Степановна', scienceDegree: 'Преподаватель', faculty: faculties[7], role: 'Работник' },
	{ id: 34, firstName: 'Руслан', lastName: 'Сидоров', surName: 'Романович', scienceDegree: 'Преподаватель', faculty: faculties[7], role: 'Декан' },
	{ id: 35, firstName: 'Ева', lastName: 'Фомина', surName: 'Борисовна', scienceDegree: 'Доцент', faculty: faculties[7], role: 'Зав. кафедры' }
	];
export const students: ISearchPersonStudent[] = [
	{
		id: 35,
		firstName: 'Александр',
		lastName: 'Петров',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: { ...groups[0], leader: { id: 35 } },
	},
	{
		id: 36,
		firstName: 'Елизавета',
		lastName: 'Степанова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: { ...groups[1], leader: { id: 36 } },
	},
	{
		id: 37,
		firstName: 'Артем',
		lastName: 'Семенов',
		surName: '',
		isStudent: true,
		faculty: faculties[1],
		group: { ...groups[2], leader: { id: 37 } },
	},
	{
		id: 38,
		firstName: 'Виктория',
		lastName: 'Романова',
		surName: '',
		isStudent: true,
		faculty: faculties[2],
		group: { ...groups[3], leader: { id: 38 } },
	},
	{
		id: 39,
		firstName: 'Антон',
		lastName: 'Никитин',
		surName: '',
		isStudent: true,
		faculty: faculties[2],
		group: { ...groups[4], leader: { id: 39 } },
	},
	{
		id: 40,
		firstName: 'Антон',
		lastName: 'Никитин',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 41,
		firstName: 'Дарья',
		lastName: 'Захарова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 42,
		firstName: 'Михаил',
		lastName: 'Борисов',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 43,
		firstName: 'Полина',
		lastName: 'Федорова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 44,
		firstName: 'Денис',
		lastName: 'Тимофеев',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 45,
		firstName: 'Ксения',
		lastName: 'Кузнецова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[0],
	},
	{
		id: 46,
		firstName: 'Владислав',
		lastName: 'Соколов',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	},
	{
		id: 47,
		firstName: 'Анастасия',
		lastName: 'Лебедева',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	},
	{
		id: 48,
		firstName: 'Иван',
		lastName: 'Козлов',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	},
	{
		id: 49,
		firstName: 'Екатерина',
		lastName: 'Новикова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	},
	{
		id: 50,
		firstName: 'Максим',
		lastName: 'Попов',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	},
	{
		id: 51,
		firstName: 'Наталья',
		lastName: 'Виноградова',
		surName: '',
		isStudent: true,
		faculty: faculties[0],
		group: groups[1],
	}
]